### ISSUE TITLE
Literal type `dict[str, FieldMetadata]` breaks on Python <= 3.8

### ISSUE THREAD

**Issue by aarora08** [fireblocks/fireblocks-sdk-py#154]
**Describe the bug**
The `ContractUploadRequest` class uses a literal `dict` to type hints the `input_fields_metadata` parameter. Literal type hints are supported from Python 3.9 onward. 

**To Reproduce**
1. Setup Python 3.8 or lower environment
2. `import fireblocks_sdk` 
3. See an error as 
```
input_fields_metadata: Optional[dict[str, FieldMetadata]] = None,
TypeError: 'type' object is not subscriptable
```

**Expected behavior**
Able to import `fireblocks_sdk` on Python >= 3.6  

**Versions (please complete the following information):**
 - Python Version: 3.8.8
 - fireblocks-sdk version: v2.2.1

**Additional context**
The bug was introduced in PR fireblocks/fireblocks-sdk-py#146

**Comment by YoavBZ** [comment]
Thanks @aarora08 for raising this issue! We've released a fix in v2.2.2
