### ISSUE TITLE
cannot import name 'StrEnum' from 'enum'

### ISSUE THREAD

**Issue by juliocepar** [fireblocks/fireblocks-sdk-py#164]
**Describe the bug**
In Python 3.9 and fireblocks_sdk 2.5.0, I can't run any code importing anything from `fireblocks_sdk`.

**To Reproduce**

Run the following snippet:
```python
from fireblocks_sdk import FireblocksSDK

with open('FIREBLOCKS_SECRET_KEY_PATH', 'r') as file:
    fireblocks = FireblocksSDK(
        private_key=file.read(),
        api_key='FIREBLOCKS_API_KEY',
        api_base_url='https://api.fireblocks.io'
    )
```

**Expected behavior**
The code runs with no exceptions.

**Screenshots**

![image](https://github.com/fireblocks/fireblocks-sdk-py/assets/22757501/456dfeb5-fa3b-4230-b54c-4f7f74dc0181)

**Versions (please complete the following information):**
 - Python Version: 3.9.5
 - fireblocks-sdk version: 2.5.0

**Additional context**
This snippet was run in Windows 11

**Workaround**
I downgraded fireblocks_sdk to 2.4.0 and the code runs with no exceptions.

**Comment by YoavBZ** [comment]
Thanks @juliocepar for raising this!
A fix has been released in version 2.5.1
