### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by skinderis** [fireblocks/fireblocks-sdk-py#35]
```
/usr/local/lib/python3.8/site-packages/fireblocks_sdk/sdk.py in get_vault_accounts(self, name_prefix, name_suffix, min_amount_threshold)
     51             url = url + "?" + urllib.parse.urlencode(params)
     52 
---> 53         return self._get_request(url)
     54 
     55     def get_vault_account(self, vault_account_id):

/usr/local/lib/python3.8/site-packages/fireblocks_sdk/sdk.py in _get_request(self, path)
   1021 
   1022     def _get_request(self, path):
-> 1023         token = self.token_provider.sign_jwt(path)
   1024         headers = {
   1025             "X-API-Key": self.api_key,

/usr/local/lib/python3.8/site-packages/fireblocks_sdk/sdk_token_provider.py in sign_jwt(self, path, body_json)
     26         }
     27 
---> 28         return jwt.encode(token, key=self.private_key, algorithm="RS256").decode('utf-8')

AttributeError: 'str' object has no attribute 'decode'

```

**Comment by MichaelAOlson** [comment]
@skinderis `jwt.encode` from PyJWT should return a `bytes` type object, which has the `decode` attribute. This at least works for me in fireblocks-sdk v1.5.20, the latest as of this comment, and PyJWT v1.7.1. You may want to check your PYTHONPATH for anything that may be overwriting `jwt`, or potentially against different versions of fireblocks-sdk/PyJWT/other jwt libraries.

**Comment by yarinvak** [comment]
Hey @skinderis , did you manage to solve the issue? Can we close it?

**Comment by skinderis** [comment]
hey @yarinvak , the issue is that fireblocks-sdk uses pyjwt **1.7.1** version, some of my libraries are requiring newest version **2.1.0**. So basically the issue was that I had **2.1.0** version pyjwt and encode returned string, instead of bytes. @MichaelAOlson

**Comment by yarinvak** [comment]
https://github.com/fireblocks/fireblocks-sdk-py/pull/47 resolves
