### ISSUE TITLE
FireblocksApiException does not contain the error code

### ISSUE THREAD

**Issue by selevit** [fireblocks/fireblocks-sdk-py#37]
When getting a 4xx or 5xx response, the sdk raises `FireblocksApiException`, with the following args:

```python
('Got an error from fireblocks server: {"message":"The external tx id that was provided in the request, already exists","code":1438}',)
```

Error code is presented inside the error message, which is tricky to parse and extract. Would be great to have the `error_code` integer property in `FireblocksApiException`.

**Comment by yarinvak** [comment]
included in v1.9.0 thanks for the suggestion
