### ISSUE TITLE
`get_exchange_account_asset()` returns the wrong asset

### ISSUE THREAD

**Issue by oliverschwartz** [fireblocks/fireblocks-sdk-py#64]
**The bug**
When I make a call to this endpoint, the API returns the wrong asset _despite this asset being present in the vault account_.

**To Reproduce**
```
DEBUG:urllib3.connectionpool:https://api.fireblocks.io:443 "GET /v1/exchange_accounts/vault_acct_id/BTC HTTP/1.1" 200 88
{'id': 'ETH', 'balance': '0.2', 'total': '0.2', 'available': '0.2', 'lockedAmount': '0.00000000'}
```

**Versions (please complete the following information):**
 - Python Version: 3.6.8
 - fireblocks-sdk version: 1.12.2

**Comment by yarinvak** [comment]
@oliverschwartz Thanks for reporting the issue.
It should be fixed by now.
Please next time if you experience an issue with our API contact Fireblocks Support, the issues in Github should be related only to issues in our sdk.

**Comment by oliverschwartz** [comment]
No problem, thanks for the quick fix.
